openapi: 3.0.1
info:
  title: OnlineLibrary
  version: '1.0'
servers:
  - url: 'http://localhost:8081'
tags:
  - name: profile
    description: Profile endpoint
  - name: book
    description: Endpoints related with books
  - name: customer
    description: Endpoints related with customer
paths:
  '/api/customer/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: The id of the user
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
        description: Patch user properties to update.
      deprecated: true
      parameters: []
      tags:
        - customer
    delete:
      summary: ''
      operationId: delete-customer-userId
      responses:
        '200':
          description: OK
    tags:
      - customer
    put:
      summary: ''
      operationId: put-customer-userId
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      parameters: []
      tags:
        - customer
    get:
      summary: ''
      operationId: get-api-customer-userId
      responses:
        '200':
          description: OK
      parameters: []
      tags:
        - customer
  '/api/book/{bookId}':
    parameters:
      - schema:
          type: string
        name: bookId
        in: path
        required: true
    patch:
      summary: Update User Information
      operationId: patch-api-book-bookId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    emailVerified: false
                    createDate: '2019-08-24'
        '401':
          description: Email Already Taken
        '404':
          description: User Not Found
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
        description: Patch user properties to update.
      deprecated: true
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      tags:
        - book
    delete:
      summary: ''
      operationId: delete-api-book-bookId
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      tags:
        - book
    put:
      summary: ''
      operationId: put-api-book-bookId
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      tags:
        - book
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
    get:
      summary: ''
      operationId: get-api-book-bookId
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      tags:
        - book
  /api/customer:
    parameters: []
    post:
      summary: ''
      operationId: post-customer-userId
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples: {}
        description: ''
      tags:
        - customer
  /api/profile:
    parameters: []
    post:
      summary: ''
      operationId: post-profile
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      tags:
        - profile
  /api/book:
    parameters: []
    post:
      summary: ''
      operationId: post-book
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
            examples: {}
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
      tags:
        - book
components:
  schemas:
    User:
      title: User
      description: ''
      examples:
        - id: string
          firstName: string
          lastName: string
          email: string
          userType: USER
        - id: string
          firstName: string
          lastName: string
          email: string
          userType: USER
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        userType:
          type: string
          enum:
            - USER
            - ADMIN
        password:
          type: string
    Book:
      title: Book
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum:
            - FICTION
            - COMIC
            - ACTION
            - THRILLER
            - TECH
            - POETRY
            - DRAMA
            - OTHERS
        price:
          type: integer
        isbn:
          type: string
      examples:
        - id: string
          name: string
          type: FICTION
          price: 0
          isbn: string
